services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bank_simulator'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=bank_admin'
    ports:
      - '35222:5432'
    volumes:
      - bank_simulator:/var/lib/postgresql/data

volumes:
  bank_simulator: